"""
Create the data-lake bronze tables: raw_source_records and lake_ingest_state.

raw_source_records is the immutable, multi-source landing table for the Hive
Mind lake (email is the first source; Teams meetings etc. land here later).
Idempotency is enforced by a UNIQUE (source, external_id) constraint plus a
content_hash that detects real content changes. lake_ingest_state holds the
per-source incremental poll watermark.

Usage:
    ENVIRONMENT=sandbox python migrations/add_lake_tables.py
    ENVIRONMENT=sandbox python migrations/add_lake_tables.py --yes
    python migrations/add_lake_tables.py --database-url postgresql://...

The script is idempotent and safe to run multiple times.
"""

import argparse
import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import OperationalError, ProgrammingError


def resolve_database_url(cli_url):
    if cli_url:
        return cli_url.strip(), "explicit --database-url"

    import app.config  # noqa: F401  (triggers .env load)
    from app.db_config import get_database_config

    environment = (
        os.environ.get("FLASK_ENV")
        or os.environ.get("ENVIRONMENT", "local")
    ).lower()

    database_url, _ = get_database_config(environment)
    return database_url, environment


def confirm_target(environment, database_url, assume_yes):
    redacted = database_url
    if "@" in redacted:
        scheme_split = redacted.split("://", 1)
        if len(scheme_split) == 2:
            scheme, rest = scheme_split
            if "@" in rest:
                creds, host = rest.split("@", 1)
                user = creds.split(":", 1)[0]
                redacted = f"{scheme}://{user}:***@{host}"

    print(f"Environment: {environment}")
    print(f"Database:    {redacted}")

    is_local = environment in ("local", "development", "dev") or database_url.startswith("sqlite")
    if is_local or assume_yes:
        return True

    answer = input("Proceed with migration? [y/N]: ").strip().lower()
    return answer in ("y", "yes")


def table_exists(engine, table_name):
    return table_name in inspect(engine).get_table_names()


def _create_raw_source_records(conn, is_postgres):
    json_type = "JSONB" if is_postgres else "JSON"
    timestamp_default = "CURRENT_TIMESTAMP"
    identity_clause = "GENERATED BY DEFAULT AS IDENTITY" if is_postgres else "AUTOINCREMENT"

    conn.execute(text(f"""
        CREATE TABLE raw_source_records (
            id INTEGER PRIMARY KEY {identity_clause},
            source VARCHAR(64) NOT NULL,
            record_type VARCHAR(64) NOT NULL,
            source_account VARCHAR(255),
            external_id VARCHAR(1024) NOT NULL,
            content_hash VARCHAR(64) NOT NULL,
            occurred_at TIMESTAMP,
            ingested_at TIMESTAMP NOT NULL DEFAULT {timestamp_default},
            payload {json_type} NOT NULL,
            external_pointer {json_type},
            CONSTRAINT uq_raw_source_external_id UNIQUE (source, external_id)
        )
    """))
    conn.execute(text(
        "CREATE INDEX IF NOT EXISTS ix_raw_source_records_content_hash "
        "ON raw_source_records (content_hash)"
    ))
    conn.execute(text(
        "CREATE INDEX IF NOT EXISTS ix_raw_source_records_occurred_at "
        "ON raw_source_records (occurred_at)"
    ))


def _create_lake_ingest_state(conn, is_postgres):
    timestamp_default = "CURRENT_TIMESTAMP"
    identity_clause = "GENERATED BY DEFAULT AS IDENTITY" if is_postgres else "AUTOINCREMENT"

    conn.execute(text(f"""
        CREATE TABLE lake_ingest_state (
            id INTEGER PRIMARY KEY {identity_clause},
            source VARCHAR(64) NOT NULL,
            account VARCHAR(255),
            last_polled_at TIMESTAMP,
            last_occurred_at TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT {timestamp_default},
            CONSTRAINT uq_lake_ingest_source_account UNIQUE (source, account)
        )
    """))


def migrate(database_url):
    engine = create_engine(database_url)
    is_postgres = database_url.startswith("postgresql://") or database_url.startswith("postgres://")

    try:
        created_any = False
        with engine.begin() as conn:
            if table_exists(engine, "raw_source_records"):
                print("✓ Table 'raw_source_records' already exists. Skipping.")
            else:
                print("Creating table 'raw_source_records'...")
                _create_raw_source_records(conn, is_postgres)
                created_any = True

            if table_exists(engine, "lake_ingest_state"):
                print("✓ Table 'lake_ingest_state' already exists. Skipping.")
            else:
                print("Creating table 'lake_ingest_state'...")
                _create_lake_ingest_state(conn, is_postgres)
                created_any = True

        ok = table_exists(engine, "raw_source_records") and table_exists(engine, "lake_ingest_state")
        if ok:
            print("✓ Lake tables present." if not created_any else "✓ Successfully created lake tables.")
            return True

        print("✗ Table creation did not succeed. Please verify manually.")
        return False

    except (OperationalError, ProgrammingError) as exc:
        print(f"✗ Database error while creating tables: {exc}")
        return False
    except Exception as exc:
        print(f"✗ Unexpected error: {exc}")
        return False
    finally:
        engine.dispose()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create data-lake bronze tables.")
    parser.add_argument(
        "--database-url",
        help="Override database URL (otherwise resolved from ENVIRONMENT/FLASK_ENV).",
    )
    parser.add_argument(
        "-y", "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt for sandbox/production.",
    )
    args = parser.parse_args()

    try:
        database_url, environment = resolve_database_url(args.database_url)
    except ValueError as exc:
        print(f"✗ {exc}")
        sys.exit(2)

    if not confirm_target(environment, database_url, args.yes):
        print("Aborted by user.")
        sys.exit(1)

    success = migrate(database_url)
    sys.exit(0 if success else 1)
