"""
Create the sunbelt_rental_snapshots and sunbelt_rentals tables for the Sunbelt
Equipment-on-Rent reporting feature.

Usage:
    # Pick the environment via ENVIRONMENT (or FLASK_ENV) env var, exactly the
    # same way the app does. Loads .env automatically via app.config import.
    ENVIRONMENT=sandbox python migrations/add_sunbelt_rentals_tables.py

    # Skip the interactive confirmation when targeting sandbox/production:
    ENVIRONMENT=sandbox python migrations/add_sunbelt_rentals_tables.py --yes

    # Or pass an explicit database URL (overrides ENVIRONMENT):
    python migrations/add_sunbelt_rentals_tables.py --database-url postgresql://...

The script is idempotent and safe to run multiple times.
"""

import argparse
import os
import sys

# Make the repo root importable so `import app.config` works regardless of CWD.
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import OperationalError, ProgrammingError


def resolve_database_url(cli_url: str | None) -> tuple[str, str]:
    """Pick the DB URL to migrate against. Returns (url, environment_label)."""
    if cli_url:
        return cli_url.strip(), "explicit --database-url"

    # Importing app.config triggers load_dotenv on the repo's .env file.
    import app.config  # noqa: F401

    from app.db_config import get_database_config

    environment = (
        os.environ.get("FLASK_ENV")
        or os.environ.get("ENVIRONMENT", "local")
    ).lower()

    database_url, _engine_options = get_database_config(environment)
    return database_url, environment


def confirm_target(environment: str, database_url: str, assume_yes: bool) -> bool:
    """Prompt before mutating sandbox/production. Local DBs require no prompt."""
    redacted = database_url
    if "@" in redacted:
        scheme_split = redacted.split("://", 1)
        if len(scheme_split) == 2:
            scheme, rest = scheme_split
            if "@" in rest:
                creds, host = rest.split("@", 1)
                user = creds.split(":", 1)[0]
                redacted = f"{scheme}://{user}:***@{host}"

    print(f"Environment: {environment}")
    print(f"Database:    {redacted}")

    is_local = environment in ("local", "development", "dev") or database_url.startswith("sqlite")
    if is_local or assume_yes:
        return True

    answer = input("Proceed with migration? [y/N]: ").strip().lower()
    return answer in ("y", "yes")


def table_exists(engine, table_name: str) -> bool:
    return table_name in inspect(engine).get_table_names()


def migrate(database_url: str) -> bool:
    engine = create_engine(database_url)
    is_postgres = database_url.startswith("postgresql://") or database_url.startswith("postgres://")

    identity_clause = "GENERATED BY DEFAULT AS IDENTITY" if is_postgres else "AUTOINCREMENT"
    timestamp_default = "CURRENT_TIMESTAMP"

    try:
        created_any = False

        if table_exists(engine, "sunbelt_rental_snapshots"):
            print("✓ Table 'sunbelt_rental_snapshots' already exists. Skipping.")
        else:
            print("Creating table 'sunbelt_rental_snapshots'...")
            snapshots_ddl = f"""
            CREATE TABLE sunbelt_rental_snapshots (
                id INTEGER PRIMARY KEY {identity_clause},
                snapshot_date DATE NOT NULL,
                source VARCHAR(20) NOT NULL DEFAULT 'upload',
                filename VARCHAR(512),
                row_count INTEGER NOT NULL DEFAULT 0,
                created_by VARCHAR(255),
                created_at TIMESTAMP NOT NULL DEFAULT {timestamp_default}
            )
            """
            with engine.begin() as conn:
                conn.execute(text(snapshots_ddl))
                conn.execute(text(
                    "CREATE INDEX IF NOT EXISTS ix_sunbelt_rental_snapshots_date "
                    "ON sunbelt_rental_snapshots (snapshot_date)"
                ))
            created_any = True

        if table_exists(engine, "sunbelt_rentals"):
            print("✓ Table 'sunbelt_rentals' already exists. Skipping.")
        else:
            print("Creating table 'sunbelt_rentals'...")
            rentals_ddl = f"""
            CREATE TABLE sunbelt_rentals (
                id INTEGER PRIMARY KEY {identity_clause},
                snapshot_id INTEGER NOT NULL REFERENCES sunbelt_rental_snapshots(id) ON DELETE CASCADE,
                contract_number VARCHAR(40),
                sunbelt_job_label VARCHAR(255),
                po_number VARCHAR(40),
                job_location VARCHAR(500),
                ordered_by VARCHAR(255),
                equipment_type VARCHAR(255),
                equipment_number VARCHAR(64),
                make VARCHAR(64),
                model VARCHAR(64),
                quantity INTEGER DEFAULT 1,
                est_return_date DATE,
                day_rate NUMERIC(10, 2),
                week_rate NUMERIC(10, 2),
                four_week_rate NUMERIC(10, 2),
                billed_through DATE,
                date_rented DATE,
                matched_job_number INTEGER,
                matched_project_name VARCHAR(255),
                match_method VARCHAR(20)
            )
            """
            with engine.begin() as conn:
                conn.execute(text(rentals_ddl))
                conn.execute(text(
                    "CREATE INDEX IF NOT EXISTS ix_sunbelt_rentals_snapshot "
                    "ON sunbelt_rentals (snapshot_id)"
                ))
                conn.execute(text(
                    "CREATE INDEX IF NOT EXISTS ix_sunbelt_rentals_contract "
                    "ON sunbelt_rentals (contract_number)"
                ))
            created_any = True

        if table_exists(engine, "sunbelt_rental_snapshots") and table_exists(engine, "sunbelt_rentals"):
            print("✓ Successfully created Sunbelt rental tables." if created_any
                  else "✓ Nothing to do — both tables already present.")
            return True

        print("✗ Table creation did not succeed. Please verify manually.")
        return False

    except (OperationalError, ProgrammingError) as exc:
        print(f"✗ Database error while creating tables: {exc}")
        return False
    except Exception as exc:  # pragma: no cover - defensive logging
        print(f"✗ Unexpected error: {exc}")
        return False
    finally:
        engine.dispose()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create Sunbelt rental tables.")
    parser.add_argument(
        "--database-url",
        help="Override database URL (otherwise resolved from ENVIRONMENT/FLASK_ENV).",
    )
    parser.add_argument(
        "-y", "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt for sandbox/production.",
    )
    args = parser.parse_args()

    try:
        database_url, environment = resolve_database_url(args.database_url)
    except ValueError as exc:
        print(f"✗ {exc}")
        sys.exit(2)

    if not confirm_target(environment, database_url, args.yes):
        print("Aborted by user.")
        sys.exit(1)

    success = migrate(database_url)
    sys.exit(0 if success else 1)
