"""
Create the release_drawing_versions table for the PDF markup feature.

Usage:
    # Pick the environment via ENVIRONMENT (or FLASK_ENV) env var, exactly the
    # same way the app does. Loads .env automatically via app.config import.
    ENVIRONMENT=sandbox python migrations/add_release_drawing_versions_table.py

    # Skip the interactive confirmation when targeting sandbox/production:
    ENVIRONMENT=sandbox python migrations/add_release_drawing_versions_table.py --yes

    # Or pass an explicit database URL (overrides ENVIRONMENT):
    python migrations/add_release_drawing_versions_table.py --database-url postgresql://...

The script is idempotent and safe to run multiple times.
"""

import argparse
import os
import sys

# Make the repo root importable so `import app.config` works regardless of CWD.
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import OperationalError, ProgrammingError


def resolve_database_url(cli_url: str | None) -> tuple[str, str]:
    """Pick the DB URL to migrate against. Returns (url, environment_label).

    Priority:
      1. --database-url CLI flag
      2. The same resolution the app uses, keyed off ENVIRONMENT/FLASK_ENV
         (sandbox→SANDBOX_DATABASE_URL, production→PRODUCTION/DATABASE_URL,
         local→LOCAL_DATABASE_URL or sqlite:///jobs.sqlite).
    """
    if cli_url:
        return cli_url.strip(), "explicit --database-url"

    # Importing app.config triggers load_dotenv on the repo's .env file.
    import app.config  # noqa: F401

    from app.db_config import get_database_config

    environment = (
        os.environ.get("FLASK_ENV")
        or os.environ.get("ENVIRONMENT", "local")
    ).lower()

    database_url, _engine_options = get_database_config(environment)
    return database_url, environment


def confirm_target(environment: str, database_url: str, assume_yes: bool) -> bool:
    """Prompt before mutating sandbox/production. Local DBs require no prompt."""
    redacted = database_url
    if "@" in redacted:
        # Hide password while still showing the host so the user can confirm.
        scheme_split = redacted.split("://", 1)
        if len(scheme_split) == 2:
            scheme, rest = scheme_split
            if "@" in rest:
                creds, host = rest.split("@", 1)
                user = creds.split(":", 1)[0]
                redacted = f"{scheme}://{user}:***@{host}"

    print(f"Environment: {environment}")
    print(f"Database:    {redacted}")

    is_local = environment in ("local", "development", "dev") or database_url.startswith("sqlite")
    if is_local or assume_yes:
        return True

    answer = input("Proceed with migration? [y/N]: ").strip().lower()
    return answer in ("y", "yes")


def table_exists(engine, table_name: str) -> bool:
    return table_name in inspect(engine).get_table_names()


def migrate(database_url: str) -> bool:
    engine = create_engine(database_url)
    is_postgres = database_url.startswith("postgresql://") or database_url.startswith("postgres://")

    try:
        if table_exists(engine, "release_drawing_versions"):
            print("✓ Table 'release_drawing_versions' already exists. Nothing to do.")
            return True

        print("Creating table 'release_drawing_versions'...")

        false_default = "FALSE" if is_postgres else "0"
        bigint_type = "BIGINT"
        timestamp_default = "CURRENT_TIMESTAMP"
        identity_clause = (
            "GENERATED BY DEFAULT AS IDENTITY" if is_postgres else "AUTOINCREMENT"
        )

        ddl = f"""
        CREATE TABLE release_drawing_versions (
            id INTEGER PRIMARY KEY {identity_clause},
            release_id INTEGER NOT NULL REFERENCES releases(id),
            version_number INTEGER NOT NULL,
            storage_key VARCHAR(512) NOT NULL,
            original_filename VARCHAR(256),
            mime_type VARCHAR(64) NOT NULL DEFAULT 'application/pdf',
            file_size_bytes {bigint_type} NOT NULL,
            uploaded_by_user_id INTEGER NOT NULL REFERENCES users(id),
            uploaded_at TIMESTAMP NOT NULL DEFAULT {timestamp_default},
            source_version_id INTEGER REFERENCES release_drawing_versions(id),
            note TEXT,
            is_deleted BOOLEAN NOT NULL DEFAULT {false_default},
            CONSTRAINT _release_version_uc UNIQUE (release_id, version_number)
        )
        """

        with engine.begin() as conn:
            conn.execute(text(ddl))
            conn.execute(text(
                "CREATE INDEX IF NOT EXISTS ix_release_drawing_versions_release_id "
                "ON release_drawing_versions (release_id)"
            ))

        if table_exists(engine, "release_drawing_versions"):
            print("✓ Successfully created 'release_drawing_versions' table.")
            return True

        print("✗ Table creation did not succeed. Please verify manually.")
        return False

    except (OperationalError, ProgrammingError) as exc:
        print(f"✗ Database error while creating table: {exc}")
        return False
    except Exception as exc:  # pragma: no cover - defensive logging
        print(f"✗ Unexpected error: {exc}")
        return False
    finally:
        engine.dispose()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create release_drawing_versions table.")
    parser.add_argument(
        "--database-url",
        help="Override database URL (otherwise resolved from ENVIRONMENT/FLASK_ENV).",
    )
    parser.add_argument(
        "-y", "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt for sandbox/production.",
    )
    args = parser.parse_args()

    try:
        database_url, environment = resolve_database_url(args.database_url)
    except ValueError as exc:
        print(f"✗ {exc}")
        sys.exit(2)

    if not confirm_target(environment, database_url, args.yes):
        print("Aborted by user.")
        sys.exit(1)

    success = migrate(database_url)
    sys.exit(0 if success else 1)
