"""
Create the brain_drifts table — where a meeting's spoken reality diverges from the Brain.

v3 drift detection (read-only) records one row per release/submittal field the room spoke
about whose value disagrees with the system of record — both status `contradiction`s and
`agreed_change`s that never landed. See app/models.py:BrainDrift and
app/brain/meetings/brain_delta.py. This SUBSUMES the v2 checklist brain_update_pending flag
(that column is left in place; nothing here touches checklist_items).

This migration only CREATES a table (no ALTER on a hot table). Idempotent and safe to
re-run. Environment → database is resolved the same way the app does (ENVIRONMENT /
FLASK_ENV via app.db_config), and sandbox/production runs prompt for confirmation.

Usage:
    ENVIRONMENT=sandbox python migrations/add_brain_drifts.py
    ENVIRONMENT=prod    python migrations/add_brain_drifts.py
    python migrations/add_brain_drifts.py --database-url postgresql://...
    python migrations/add_brain_drifts.py --yes        # skip the confirm prompt
"""

import argparse
import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import OperationalError, ProgrammingError


def resolve_database_url(cli_url):
    """Resolve the target DB the same way the app does, so ENVIRONMENT=prod/sandbox in
    .env picks the right database (importing app.config triggers the app's .env load)."""
    if cli_url:
        return cli_url.strip(), "explicit --database-url"

    import app.config  # noqa: F401  (triggers .env load)
    from app.db_config import get_database_config

    environment = (
        os.environ.get("FLASK_ENV")
        or os.environ.get("ENVIRONMENT", "local")
    ).lower()

    database_url, _ = get_database_config(environment)
    return database_url, environment


def confirm_target(environment, database_url, assume_yes):
    redacted = database_url
    if "@" in redacted:
        scheme_split = redacted.split("://", 1)
        if len(scheme_split) == 2:
            scheme, rest = scheme_split
            if "@" in rest:
                creds, host = rest.split("@", 1)
                user = creds.split(":", 1)[0]
                redacted = f"{scheme}://{user}:***@{host}"

    print(f"Environment: {environment}")
    print(f"Database:    {redacted}")

    is_local = environment in ("local", "development", "dev") or database_url.startswith("sqlite")
    if is_local or assume_yes:
        return True

    answer = input("Proceed with migration? [y/N]: ").strip().lower()
    return answer in ("y", "yes")


def table_exists(engine, table_name):
    return table_name in inspect(engine).get_table_names()


def migrate(database_url):
    engine = create_engine(database_url)
    is_postgres = database_url.startswith("postgresql://") or database_url.startswith("postgres://")

    try:
        if table_exists(engine, "brain_drifts"):
            print("✓ Table 'brain_drifts' already exists. Nothing to do.")
            return True

        print("Creating table 'brain_drifts'...")

        identity_clause = "GENERATED BY DEFAULT AS IDENTITY" if is_postgres else "AUTOINCREMENT"

        # FK columns reference the (hot) releases/submittals tables. Adding an FK takes a
        # brief share lock on the referenced table on Postgres; lock_timeout makes that
        # fail fast instead of queueing behind live traffic. CREATE TABLE itself never
        # touches other tables.
        ddl = f"""
        CREATE TABLE brain_drifts (
            id INTEGER PRIMARY KEY {identity_clause},
            meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
            target VARCHAR(12) NOT NULL,
            ref VARCHAR(64),
            entity_name VARCHAR(255),
            field VARCHAR(40) NOT NULL,
            stated_value VARCHAR(255),
            brain_value VARCHAR(255),
            kind VARCHAR(20) NOT NULL DEFAULT 'contradiction',
            quote TEXT,
            confidence DOUBLE PRECISION,
            release_id INTEGER REFERENCES releases(id),
            submittal_id VARCHAR(255) REFERENCES submittals(submittal_id),
            status VARCHAR(20) NOT NULL DEFAULT 'open',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """

        with engine.begin() as conn:
            if is_postgres:
                conn.execute(text("SET lock_timeout = '5s'"))
            conn.execute(text(ddl))
            conn.execute(text(
                "CREATE INDEX IF NOT EXISTS ix_brain_drifts_meeting_id "
                "ON brain_drifts (meeting_id)"
            ))

        if table_exists(engine, "brain_drifts"):
            print("✓ Successfully created 'brain_drifts' table.")
            return True

        print("✗ Table creation did not succeed. Please verify manually.")
        return False

    except (OperationalError, ProgrammingError) as exc:
        print(f"✗ Database error while creating table: {exc}")
        return False
    except Exception as exc:
        print(f"✗ Unexpected error: {exc}")
        return False
    finally:
        engine.dispose()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create the brain_drifts table.")
    parser.add_argument(
        "--database-url",
        help="Override database URL (otherwise resolved from ENVIRONMENT/FLASK_ENV).",
    )
    parser.add_argument(
        "-y", "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt for sandbox/production.",
    )
    args = parser.parse_args()

    try:
        database_url, environment = resolve_database_url(args.database_url)
    except ValueError as exc:
        print(f"✗ {exc}")
        sys.exit(2)

    if not confirm_target(environment, database_url, args.yes):
        print("Aborted by user.")
        sys.exit(1)

    success = migrate(database_url)
    sys.exit(0 if success else 1)
