"""
Migration: create + seed the `installer_teams` table.

Installer crews are first-class records managed via the admin "Edit Crews" UI on
the PM board. Each crew has a name (kept identical to its Trello list name) and a
`crew_size` (number of installers). The crew_size of a release's assigned crew
drives that release's completion ETA (install_hrs / (crew_size × 8h) business days).

`trello_list_id` lets the mirror-card move resolve a list id without a name lookup
during the Trello transition; it may be null and is backfilled lazily.

Usage:
    # Pick the environment via ENVIRONMENT (or FLASK_ENV), same as the app.
    ENVIRONMENT=sandbox python migrations/add_installer_teams.py

    # Skip the interactive confirmation when targeting sandbox/production:
    ENVIRONMENT=sandbox python migrations/add_installer_teams.py --yes

    # Or pass an explicit database URL (overrides ENVIRONMENT):
    python migrations/add_installer_teams.py --database-url postgresql://...

The script is idempotent and safe to run multiple times.
"""

import argparse
import os
import sys

# Make the repo root importable so `import app.config` works regardless of CWD.
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import OperationalError, ProgrammingError


def resolve_database_url(cli_url):
    """Pick the DB URL to migrate against. Returns (url, environment_label)."""
    if cli_url:
        return cli_url.strip(), "explicit --database-url"

    # Importing app.config triggers load_dotenv on the repo's .env file.
    import app.config  # noqa: F401

    from app.db_config import get_database_config

    environment = (
        os.environ.get("FLASK_ENV")
        or os.environ.get("ENVIRONMENT", "local")
    ).lower()

    database_url, _engine_options = get_database_config(environment)
    return database_url, environment


def confirm_target(environment, database_url, assume_yes):
    """Prompt before mutating sandbox/production. Local DBs require no prompt."""
    redacted = database_url
    if "@" in redacted:
        scheme_split = redacted.split("://", 1)
        if len(scheme_split) == 2:
            scheme, rest = scheme_split
            if "@" in rest:
                creds, host = rest.split("@", 1)
                user = creds.split(":", 1)[0]
                redacted = f"{scheme}://{user}:***@{host}"

    print(f"Environment: {environment}")
    print(f"Database:    {redacted}")

    is_local = environment in ("local", "development", "dev") or database_url.startswith("sqlite")
    if is_local or assume_yes:
        return True

    answer = input("Proceed with migration? [y/N]: ").strip().lower()
    return answer in ("y", "yes")


def table_exists(engine, table_name):
    return table_name in inspect(engine).get_table_names()


def seed_installer_teams(conn):
    """Seed installer_teams from Config.INSTALLER_TEAMS (idempotent by name)."""
    from app.config import Config

    names = [n for n in (Config.INSTALLER_TEAMS or []) if n and n.strip()]
    if not names:
        print("  (no INSTALLER_TEAMS configured; skipping seed)")
        return

    existing = {
        row[0] for row in conn.execute(text("SELECT name FROM installer_teams")).fetchall()
    }
    for name in names:
        name = name.strip()
        if name in existing:
            continue
        conn.execute(
            text(
                "INSERT INTO installer_teams (name, crew_size, is_active) "
                "VALUES (:name, 2, :active)"
            ),
            {"name": name, "active": True},
        )
        print(f"  seeded installer crew: {name}")


def migrate(database_url):
    engine = create_engine(database_url)
    is_postgres = database_url.startswith("postgresql://") or database_url.startswith("postgres://")
    identity_clause = "GENERATED BY DEFAULT AS IDENTITY" if is_postgres else "AUTOINCREMENT"
    true_default = "TRUE" if is_postgres else "1"

    try:
        with engine.begin() as conn:
            if table_exists(engine, "installer_teams"):
                print("✓ Table 'installer_teams' already exists.")
            else:
                print("Creating table 'installer_teams'...")
                conn.execute(text(f"""
                    CREATE TABLE installer_teams (
                        id INTEGER PRIMARY KEY {identity_clause},
                        name VARCHAR(64) NOT NULL UNIQUE,
                        crew_size INTEGER NOT NULL DEFAULT 2,
                        trello_list_id VARCHAR(64),
                        is_active BOOLEAN NOT NULL DEFAULT {true_default}
                    )
                """))
                print("✓ Created 'installer_teams'.")

            print("Seeding installer_teams from Config.INSTALLER_TEAMS...")
            seed_installer_teams(conn)

        return True

    except (OperationalError, ProgrammingError) as exc:
        print(f"✗ Database error during migration: {exc}")
        return False
    except Exception as exc:  # pragma: no cover - defensive logging
        print(f"✗ Unexpected error: {exc}")
        return False
    finally:
        engine.dispose()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create + seed installer_teams.")
    parser.add_argument(
        "--database-url",
        help="Override database URL (otherwise resolved from ENVIRONMENT/FLASK_ENV).",
    )
    parser.add_argument(
        "-y", "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt for sandbox/production.",
    )
    args = parser.parse_args()

    try:
        database_url, environment = resolve_database_url(args.database_url)
    except ValueError as exc:
        print(f"✗ {exc}")
        sys.exit(2)

    if not confirm_target(environment, database_url, args.yes):
        print("Aborted by user.")
        sys.exit(1)

    success = migrate(database_url)
    sys.exit(0 if success else 1)
