"""
Create the microsoft_delegated_tokens table.

Stores the delegated OAuth token (device-code flow) for a single mailbox
identity — bb@mhmw.com — used when org policy blocks app-only Graph
application permissions. One row per account_email; tokens are TEXT (no length
cap) since refresh tokens are large.

Usage:
    ENVIRONMENT=sandbox python migrations/add_microsoft_delegated_tokens.py
    ENVIRONMENT=sandbox python migrations/add_microsoft_delegated_tokens.py --yes
    python migrations/add_microsoft_delegated_tokens.py --database-url postgresql://...

The script is idempotent and safe to run multiple times.
"""

import argparse
import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import OperationalError, ProgrammingError


def resolve_database_url(cli_url):
    if cli_url:
        return cli_url.strip(), "explicit --database-url"

    import app.config  # noqa: F401  (triggers .env load)
    from app.db_config import get_database_config

    environment = (
        os.environ.get("FLASK_ENV")
        or os.environ.get("ENVIRONMENT", "local")
    ).lower()

    database_url, _ = get_database_config(environment)
    return database_url, environment


def confirm_target(environment, database_url, assume_yes):
    redacted = database_url
    if "@" in redacted:
        scheme_split = redacted.split("://", 1)
        if len(scheme_split) == 2:
            scheme, rest = scheme_split
            if "@" in rest:
                creds, host = rest.split("@", 1)
                user = creds.split(":", 1)[0]
                redacted = f"{scheme}://{user}:***@{host}"

    print(f"Environment: {environment}")
    print(f"Database:    {redacted}")

    is_local = environment in ("local", "development", "dev") or database_url.startswith("sqlite")
    if is_local or assume_yes:
        return True

    answer = input("Proceed with migration? [y/N]: ").strip().lower()
    return answer in ("y", "yes")


def table_exists(engine, table_name):
    return table_name in inspect(engine).get_table_names()


def migrate(database_url):
    engine = create_engine(database_url)
    is_postgres = database_url.startswith("postgresql://") or database_url.startswith("postgres://")

    try:
        if table_exists(engine, "microsoft_delegated_tokens"):
            print("✓ Table 'microsoft_delegated_tokens' already exists. Nothing to do.")
            return True

        print("Creating table 'microsoft_delegated_tokens'...")

        timestamp_default = "CURRENT_TIMESTAMP"
        identity_clause = "GENERATED BY DEFAULT AS IDENTITY" if is_postgres else "AUTOINCREMENT"

        ddl = f"""
        CREATE TABLE microsoft_delegated_tokens (
            id INTEGER PRIMARY KEY {identity_clause},
            account_email VARCHAR(255) NOT NULL UNIQUE,
            access_token TEXT,
            refresh_token TEXT,
            token_expires_at TIMESTAMP,
            scopes TEXT,
            updated_at TIMESTAMP NOT NULL DEFAULT {timestamp_default}
        )
        """

        with engine.begin() as conn:
            conn.execute(text(ddl))
            conn.execute(text(
                "CREATE INDEX IF NOT EXISTS ix_microsoft_delegated_tokens_account_email "
                "ON microsoft_delegated_tokens (account_email)"
            ))

        if table_exists(engine, "microsoft_delegated_tokens"):
            print("✓ Successfully created 'microsoft_delegated_tokens' table.")
            return True

        print("✗ Table creation did not succeed. Please verify manually.")
        return False

    except (OperationalError, ProgrammingError) as exc:
        print(f"✗ Database error while creating table: {exc}")
        return False
    except Exception as exc:
        print(f"✗ Unexpected error: {exc}")
        return False
    finally:
        engine.dispose()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create microsoft_delegated_tokens table.")
    parser.add_argument(
        "--database-url",
        help="Override database URL (otherwise resolved from ENVIRONMENT/FLASK_ENV).",
    )
    parser.add_argument(
        "-y", "--yes",
        action="store_true",
        help="Skip the interactive confirmation prompt for sandbox/production.",
    )
    args = parser.parse_args()

    try:
        database_url, environment = resolve_database_url(args.database_url)
    except ValueError as exc:
        print(f"✗ {exc}")
        sys.exit(2)

    if not confirm_target(environment, database_url, args.yes):
        print("Aborted by user.")
        sys.exit(1)

    success = migrate(database_url)
    sys.exit(0 if success else 1)
